[config]
bm_open_method=0

[volume]

[ui]
app_bg=#282828
app_fg=#e0e0e0
toolbar_bg=#282828
toolbar_fg=#e0e0e0
pathbar_bg=#282828
pathbar_fg=#ffffff
view_bg=#282828
view_fg=#e0e0e0
sel_bg=#3c3836
sel_fg=#e0e0e0
app_font=JetBrains Mono 11
win_width=1054
win_height=1052
side_pane_mode=places
view_mode=list
sort=name;ascending;
toolbar=newtab;navigation;home;
show_statusbar=0
