PKG         = $(HOME)/pkg
PKGIN       = git imlib2 ttf-jetbrains-mono ttf-jetbrains-mono-nerd noto-fonts base-devel github-cli lazygit fzf zoxide starship swayimg redshift
PKGRM       = ex-vi-compat vim
URL         = https://github.com/HimadriChakra12
MAKEREPOS   = fetch dtop whot det
INREPOS     = swat
MAKE_INSTALL= sudo make install
INSH      	= bash install.sh
USC			= userChrome
